import React from 'react';
import { SEO } from '../components/seo/SEO';
import { Breadcrumbs } from '../components/layout/Breadcrumbs';
import { DisclaimerNotice } from '../components/common/DisclaimerNotice';

export const TermsOfUsePage: React.FC = () => {
  const breadcrumbs = [
    { label: 'Terms of Use', path: '/terms-of-use' },
  ];

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      <SEO
        title="Terms of Use | PayWise UK"
        description="Review the terms and conditions for using PayWise UK salary calculators and educational guides."
        keywords={[
          'PayWise UK terms of use',
          'salary calculator terms',
          'tax calculator terms and conditions',
        ]}
        canonicalPath="/terms-of-use"
        breadcrumbs={breadcrumbs}
      />

      <Breadcrumbs items={breadcrumbs} />

      <header className="space-y-2">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-lg bg-[#F5F5F5] dark:bg-[#171717] border border-[#E5E5E5] dark:border-[#2A2A2A] text-[#059669] dark:text-[#10B981] text-xs font-bold shadow-xs">
          <span className="w-2 h-2 rounded-full bg-[#059669] dark:bg-[#10B981]" />
          Website Terms
        </div>
        <h1 className="text-2xl sm:text-4xl font-black text-[#111111] dark:text-[#F5F5F5] tracking-tight">
          Terms of Use
        </h1>
        <p className="text-xs sm:text-sm text-[#525252] dark:text-[#A3A3A3] leading-relaxed">
          Last updated: January 2026. Please read these terms carefully before utilizing our salary calculation tools.
        </p>
      </header>

      <div className="border border-[#E5E5E5] dark:border-[#2A2A2A] bg-white dark:bg-[#171717] rounded-2xl p-6 sm:p-8 shadow-[0_8px_30px_rgba(0,0,0,0.06)] dark:shadow-[0_10px_35px_rgba(0,0,0,0.35)] space-y-6 text-xs sm:text-sm text-[#525252] dark:text-[#A3A3A3] leading-relaxed">
        <div>
          <h2 className="text-base sm:text-lg font-bold text-[#111111] dark:text-[#F5F5F5] mb-2">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing and using PayWise UK, you acknowledge and agree to comply with these Terms of Use and our accompanying Disclaimer. If you disagree with any part of these terms, please discontinue use of the site.
          </p>
        </div>

        <div>
          <h2 className="text-base sm:text-lg font-bold text-[#111111] dark:text-[#F5F5F5] mb-2">
            2. Permitted Use & Intellectual Property
          </h2>
          <p>
            PayWise UK calculators and guides are provided for individual personal budgeting and commercial illustration purposes. You may not scrape, frame, redistribute, or reverse-engineer our calculation algorithms without express written permission.
          </p>
        </div>

        <div>
          <h2 className="text-base sm:text-lg font-bold text-[#111111] dark:text-[#F5F5F5] mb-2">
            3. Disclaimer of Financial Advice
          </h2>
          <p>
            All outputs generated by our calculators are mathematical approximations based on current statutory tax tables. They do not constitute formal financial, accounting, tax, or legal advice. Users must consult a qualified accountant or IFA before making financial commitments.
          </p>
        </div>

        <div>
          <h2 className="text-base sm:text-lg font-bold text-[#111111] dark:text-[#F5F5F5] mb-2">
            4. Limitation of Liability
          </h2>
          <p>
            PayWise UK and its operators accept no liability for financial decisions, payroll adjustments, tax underpayments, or discrepancies arising from the use of our calculations.
          </p>
        </div>
      </div>

      <DisclaimerNotice />
    </div>
  );
};
